[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
evm_version = "shanghai"
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "src=src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts",
    "@solmate/=lib/solmate/src/"
]

[fuzz]
runs = 256

[rpc_endpoints]
optimism = "${OPTIMISM_RPC_ENDPOINT}"

[etherscan]
optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options